name: Update Broker News
on:
  workflow_dispatch:
    inputs:
      counter_ids:
        description: "update broker news by input ids, e.g. 1,2,3"
        required: false
  repository_dispatch:
    types:
      - update_news

jobs:
  export:
    name: Start update broker news
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1

      - name: Run update broker news
        env:
          SUPABASE_BROKER_URL: ${{ secrets.SUPABASE_BROKER_URL }}
          SUPABASE_BROKER_KEY: ${{ secrets.SUPABASE_BROKER_KEY }}
          FEED_NEWS_LINK: ${{ secrets.FEED_NEWS_LINK }}
          FEED_DETAIL_INFO_LINK: ${{ secrets.FEED_DETAIL_INFO_LINK }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
          LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
        run: |
          bun install
          bun run news --counter_ids=${{ inputs.counter_ids }}
