name: Scheduled Update Broker News
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  export:
    name: Update Broker News
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - uses: oven-sh/setup-bun@v1

      - name: Update Broker News
        env:
          SUPABASE_BROKER_URL: ${{ secrets.SUPABASE_BROKER_URL }}
          SUPABASE_BROKER_KEY: ${{ secrets.SUPABASE_BROKER_KEY }}
          FEED_NEWS_LINK: ${{ secrets.FEED_NEWS_LINK }}
          FEED_NEWS_LINK_US: ${{ secrets.FEED_NEWS_LINK_US }}
          FEED_DETAIL_INFO_LINK: ${{ secrets.FEED_DETAIL_INFO_LINK }}
          FEED_DETAIL_INFO_LINK_US: ${{ secrets.FEED_DETAIL_INFO_LINK_US }}
          FEED_MORE_INFO_LINK: ${{ secrets.FEED_MORE_INFO_LINK }}
          FEED_MORE_INFO_LINK_US: ${{ secrets.FEED_MORE_INFO_LINK_US }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
          LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
        run: |
          bun install
          bun run news
